# Generated by Django 5.0 on 2024-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
