# Generated by Django 5.0 on 2024-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='region',
            field=models.IntegerField(choices=[(1, 'United States'), (2, 'United Kingdom'), (3, 'Germany'), (4, 'France'), (5, 'Japan'), (6, 'Russia'), (7, 'Greece'), (8, 'China'), (9, 'Italy'), (10, 'Sweden'), (11, 'Canada')], default=1),
        ),
    ]
