# Generated by Django 5.0 on 2024-02-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_address1_alter_order_address2_and_more'),
        ('product', '0004_alter_category_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='product.product'),
        ),
    ]
